version: '3'

tasks:
  setup:
    cmds:
      - docker-compose run --rm app-setup

  #############################################################################
  # START
  #############################################################################
  start:
    cmds:
      - docker-compose up -d app-dev

  #############################################################################
  # STOP
  #############################################################################
  stop:
    - docker-compose rm -svf app-dev
    
  #############################################################################
  # TASKS
  #############################################################################
  logs:
    cmds:
      - docker-compose logs -f app-dev